language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

scala:
  - 2.12.11
  - 2.13.2

services:
  - mysql
  - postgresql

jdk:
  - openjdk8

addons:
  postgresql: "9.6"

before_install:
  - psql -c "CREATE ROLE root WITH SUPERUSER LOGIN PASSWORD '';" -U postgres
  - psql -c "CREATE DATABASE akka_persistence_sql_async;" -U postgres
  - mysql -e "CREATE DATABASE akka_persistence_sql_async;" -uroot
  - sudo chmod +x /usr/local/bin/sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck test
